{% set version = '0.4-18' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-robust
  version: {{ version|replace("-", "_") }}

source:
  fn: robust_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/robust_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/robust/robust_{{ version }}.tar.gz
  sha256: e4196f01bb3b0d768759d4411d524238b627eb8dc213d84cb30014e75480f8ac

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mass
    - r-fit.models
    - r-lattice
    - r-robustbase
    - r-rrcov

  run:
    - r-base
    - r-mass
    - r-fit.models
    - r-lattice
    - r-robustbase
    - r-rrcov

test:
  commands:
    - $R -e "library('robust')"  # [not win]
    - "\"%R%\" -e \"library('robust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=robust
  license: GPL-2.0
  summary: Methods for robust statistics, a state of the art in the early 2000s, notably for
    robust regression and robust multivariate analysis.
  license_family: GPL

extra:
  recipe-maintainers:
    - bgruening
    - daler
    - johanneskoester
    - rvalieris
