{% set version = "0.7-4" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-robust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/robust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/robust/robust_{{ version }}.tar.gz
  sha256: 630d552772fd9965739d559ee53b90bed23b835592311604b060a3a0a0090862

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - r-fit.models                     # [build_platform != target_platform]
    - r-lattice                        # [build_platform != target_platform]
    - r-mass                           # [build_platform != target_platform]
    - r-robustbase                     # [build_platform != target_platform]
    - r-rrcov                          # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
  host:
    - libblas
    - liblapack
    - r-base
    - r-fit.models
    - r-lattice
    - r-mass
    - r-robustbase
    - r-rrcov
  run:
    - r-base
    - r-fit.models
    - r-lattice
    - r-mass
    - r-robustbase
    - r-rrcov

test:
  commands:
    - $R -e "library('robust')"           # [not win]
    - "\"%R%\" -e \"library('robust')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=robust
  license: GPL-2.0-only
  summary: Methods for robust statistics, a state of the art in the early 2000s, notably for robust regression and robust multivariate analysis.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - rvalieris
