appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: GZlVCnUfxmPI00ARE6oPgndE/nDEEprYVRNdMs1BN6LxO70fbbll5pCdCsRoJ59dzeCyrvkg9OVnuTCSYCC+BqxRmnaxbvUadwlbIFaLjdLTzIrlo9/hJ6fGT6Nv7X5v5amEB7BpIGoyQfAOtON8JhXJO21cLramtMopZ0R6fJYMbh5kNPyrjd1r81UOX4gjOlJ0JcdXYKbgIYJLNCoc8SqTk4qTISeo2heoHaa2Z9qXGk4PsBSjxPFw3FK9YrDXvUtGGZJQhjCdQyb5YdBzgBknIJvQLw126k5AZ0XyWJM7l7UNDFSnAvBCStRxwcZIsOYDIgedOkPnAMPzJ/kcEfN5H0DqWtnPmF5Khl0Ql4qUVNsfLFyV2evtYfCk1p4at51T8bUht4wMPIKpj3YojSh3g3qTWexQvKaLfJP3sdp+Jix1LUE1bMz8BZ7Ztb8lohNtPcYxYtJEHzeD7jcSl40NLrjKf5KSbu4PGgMhvFXiGtmnqxGuIvuYBG3ki2krcEcSPGJnyg7pyFBgpRUt5uKBioL4Xtzzq5KMCH8MVHGVYOv9rkp/DD4ihcPTVOQbVfQt6YDkv54eIXzkUjJP3AlH4xnvTCbSm2rUiqvNGLaydzwe5PqaDPfeTwBChgkApyb74J2CnKDpeJZuVy3zIPmayTZ4H8MESjbQQD8m/ws=}
bot:
  automerge: true
