travis:
  secure:
    BINSTAR_TOKEN: u+WFA6bXqG0XwazkpTgF2vCKzLPsYaGrsMrg9BC6f5OMyjxLDU0yDGfofga0RRKp6a440cv0EkS3lwKvNvPw6YxeEzCuGvH2+Of/hIPLeQyhWgJPFePsM8/zuGAu1xEwDUwwSpKxzgHztT94XKHEp5Nuh/BJ3MPPLRzbrhykuI4AJREaF5z2PgbposAmc/2dUDFm/wHSf7AqMs4EEdX4Sg2sqZYu5t6GTqg+VRw+jvCN4QoBs2KO5An2/uOYG3DkvzuR9yWmY41jmR0kw1CxS7zP1BqO1B9nWF3+N96v9KoFidHd+a84vW7pfMXbEUj82oh9WllupWJlxu1lNi8W3Iczss/dGyQravSEwDMg8/heCXVHr0zYLD+CCm7JXIJpje9wlFngPGFIxChyF3AImSvPvlbJQLEwjYZ1dLG/EQlGyH4SSZzUEh9CBhXDSsg6cPtWWhezWUhsiDv7KE0N8WapKl/hRHTffmcc+CaoriusoVXbEzO6kQGMsg+eW3/kFIa1ha/NsPNyDPduKIRFSIROo+4n/BrLoNiYe4L9HNkV76GAH3qorbJWoJ58BbJZRXYXyBBp5DRqBDHyBLDOzopSo77DTc1iDBrV5ttCrbuSEVs0k2iWJWfn4WdvknClTTZXe8gpS7MOreqIHyLmE2QoAECuzixocz1JMqYtgw4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
